version: "3.11"

services:
  db:
    image: postgres:16
    container_name: db_app
    command: -p 5432
    expose:
      - 5432
    env_file:
      - .env-non-dev

  app:
    build: 
      context: .
      args:
        DEV: "true"
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8080
    volumes:
      - ./app:/app/

