version: "3"

services:
  db:
    build: ./DB/
    ports:
      - "5432:5432"
  app:
    build: 
      context: .
      args:
        DEV: "true"
    ports:
      - "8080:8080"
    env_file:
      - .env
    command: >
      sh -c "cd /fastapi-example &&
             alembic upgrade head &&
             uvicorn main:app --reload --host 0.0.0.0 --port 8080"
    volumes:
      - ./app:/fastapi-example/app/
      - ./migrations:/fastapi-example/migrations/
      - ./alembic.ini:/fastapi-example/alembic.ini